# Generated by Django 4.1.1 on 2023-01-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.CharField(max_length=100, verbose_name='Фото товара')),
                ('description', models.CharField(max_length=100, verbose_name='Описание товара')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.CharField(max_length=100, verbose_name='Фото товара')),
                ('description', models.CharField(max_length=100, verbose_name='Описание товара')),
                ('status', models.CharField(default='В обработке', max_length=12)),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата заказа')),
                ('date_processed', models.DateField(auto_now_add=True, verbose_name='Дата последней обработки')),
                ('orderer_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='В обработке', max_length=15)),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата заказа')),
                ('date_confirmed', models.DateField(auto_now_add=True, verbose_name='Дата подтверждения')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.goods')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.userprofile')),
            ],
        ),
    ]
