# Generated by Django 4.1.1 on 2023-01-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
