# Generated by Django 4.1.1 on 2023-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='img',
        ),
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотка'),
        ),
    ]
