# Generated by Django 4.1.1 on 2023-01-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_orders_img_goods_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='img',
        ),
    ]
