# Generated by Django 4.1.1 on 2023-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_goods_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='ssilka',
            field=models.URLField(default=''),
        ),
    ]
