# Generated by Django 4.1.1 on 2023-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_goods_ssilka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_confirmed',
            field=models.DateField(auto_now=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
